In [1]:
import pandas as pd

In [2]:
data_demo = pd.read_sas('DEMO_L (1).xpt', format='xport')

In [3]:
data_demo

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,12.0,2.0,1.0,9.0,NaN,2.0,2.0,1.0,111.0,...,1.0,3.0,3.0,3.0,NaN,11147.192563,13459.129019,176.0,1.0,2.01
11929,142307.0,12.0,2.0,2.0,49.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,69419.620456,64962.328962,181.0,1.0,NaN
11930,142308.0,12.0,2.0,1.0,50.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32696.313477,44367.534132,183.0,2.0,1.95
11931,142309.0,12.0,2.0,1.0,40.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,30547.974564,46249.361849,176.0,1.0,3.11
11932,142310.0,12.0,2.0,2.0,80.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32753.585494,49647.225467,187.0,2.0,5.00

In [4]:
data_demo.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMDBORN4',
       'DMDYRUSR', 'DMDEDUC2', 'DMDMARTZ', 'RIDEXPRG', 'DMDHHSIZ', 'DMDHRGND',
       'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR',
       'SDMVSTRA', 'SDMVPSU', 'INDFMPIR'],
      dtype='object')

In [5]:
data_demo = data_demo.drop(['SDDSRVYR', 'RIDSTATR', 'RIDAGEMN','RIDRETH1','RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMDBORN4',
                            'DMDYRUSR', 'RIDEXPRG', 'DMDHHSIZ', 'DMDHRGND',
                            'DMDHRAGZ', 'DMDHREDZ', 'DMDHRMAZ', 'DMDHSEDZ', 'WTINT2YR', 'WTMEC2YR',
                            'SDMVSTRA', 'SDMVPSU' ], axis=1)

data_demo = data_demo.rename(columns={
    'RIAGENDR': 'Gender',
    'RIDRETH3': 'Race',
    'RIDAGEYR' : 'Age in years at screening',
    'DMDEDUC2': 'Education Level',
    'DMDMARTZ': 'Martial Status',
    'INDFMPIR' : 'Ratio of Family Income to Poverty'
})

SEQN : Sequence Number (Unique Identification Number).
Gender : 1 Male, 2 Female.
Age in years at screening : Evident.
Race : 1 Mexican American, 2 Other Hispanic, 3 White, 4 Black, 6 Asian, 7 Other Race and Multi Racial.

In [6]:
data_demo

,SEQN,Gender,Age in years at screening,Race,Education Level,Martial Status,Ratio of Family Income to Poverty
0,130378.0,1.0,43.0,6.0,5.0,1.0,5.00
1,130379.0,1.0,66.0,3.0,5.0,1.0,5.00
2,130380.0,2.0,44.0,2.0,3.0,1.0,1.41
3,130381.0,2.0,5.0,7.0,NaN,NaN,1.53
4,130382.0,1.0,2.0,3.0,NaN,NaN,3.60
...,...,...,...,...,...,...,...
11928,142306.0,1.0,9.0,2.0,NaN,NaN,2.01
11929,142307.0,2.0,49.0,4.0,5.0,3.0,NaN
11930,142308.0,1.0,50.0,2.0,4.0,1.0,1.95
11931,142309.0,1.0,40.0,2.0,4.0,2.0,3.11
11932,142310.0,2.0,80.0,3.0,3.0,1.0,5.00

In [7]:
data_dietary = pd.read_sas('DR1TOT_L.xpt', format = 'xport')

In [8]:
data_dietary

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,130378.0,6.136656e+04,70554.222162,1.0,73.0,2.0,2.0,40.0,4.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
1,130379.0,3.463806e+04,36505.468348,1.0,73.0,2.0,2.0,19.0,4.0,1.0,...,1.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,130380.0,8.472826e+04,103979.190677,1.0,73.0,2.0,2.0,16.0,4.0,1.0,...,NaN,2.0,NaN,2.0,NaN,1.0,4.0,2.0,NaN,2.0
3,130381.0,6.173713e+04,75009.220819,1.0,91.0,2.0,2.0,23.0,5.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
4,130382.0,7.584675e+04,172361.851828,1.0,73.0,2.0,2.0,27.0,6.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8856,142307.0,6.606603e+04,70259.160313,1.0,65.0,2.0,2.0,19.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8857,142308.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8858,142309.0,9.447764e+04,89391.946869,1.0,90.0,2.0,2.0,49.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8859,142310.0,4.787022e+04,51601.585149,1.0,89.0,2.0,2.0,19.0,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
print(list(data_dietary.columns))

['SEQN', 'WTDRD1', 'WTDR2D', 'DR1DRSTZ', 'DR1EXMER', 'DRABF', 'DRDINT', 'DR1DBIH', 'DR1DAY', 'DR1LANG', 'DR1MRESP', 'DR1HELP', 'DBQ095Z', 'DBD100', 'DRQSPREP', 'DR1STY', 'DR1SKY', 'DRQSDIET', 'DRQSDT1', 'DRQSDT2', 'DRQSDT3', 'DRQSDT4', 'DRQSDT5', 'DRQSDT6', 'DRQSDT7', 'DRQSDT8', 'DRQSDT9', 'DRQSDT10', 'DRQSDT11', 'DRQSDT12', 'DRQSDT91', 'DR1TNUMF', 'DR1TKCAL', 'DR1TPROT', 'DR1TCARB', 'DR1TSUGR', 'DR1TFIBE', 'DR1TTFAT', 'DR1TSFAT', 'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL', 'DR1TATOC', 'DR1TATOA', 'DR1TRET', 'DR1TVARA', 'DR1TACAR', 'DR1TBCAR', 'DR1TCRYP', 'DR1TLYCO', 'DR1TLZ', 'DR1TVB1', 'DR1TVB2', 'DR1TNIAC', 'DR1TVB6', 'DR1TFOLA', 'DR1TFA', 'DR1TFF', 'DR1TFDFE', 'DR1TCHL', 'DR1TVB12', 'DR1TB12A', 'DR1TVC', 'DR1TVD', 'DR1TVK', 'DR1TCALC', 'DR1TPHOS', 'DR1TMAGN', 'DR1TIRON', 'DR1TZINC', 'DR1TCOPP', 'DR1TSODI', 'DR1TPOTA', 'DR1TSELE', 'DR1TCAFF', 'DR1TTHEO', 'DR1TALCO', 'DR1TMOIS', 'DR1TS040', 'DR1TS060', 'DR1TS080', 'DR1TS100', 'DR1TS120', 'DR1TS140', 'DR1TS160', 'DR1TS180', 'DR1TM161', 'DR1TM181', 'DR1TM201', 'DR1TM221', 'DR1TP182', 'DR1TP183', 'DR1TP184', 'DR1TP204', 'DR1TP205', 'DR1TP225', 'DR1TP226', 'DR1_300', 'DR1_320Z', 'DR1_330Z', 'DR1BWATZ', 'DR1TWSZ', 'DRD340', 'DRD350A', 'DRD350AQ', 'DRD350B', 'DRD350BQ', 'DRD350C', 'DRD350CQ', 'DRD350D', 'DRD350DQ', 'DRD350E', 'DRD350EQ', 'DRD350F', 'DRD350FQ', 'DRD350G', 'DRD350GQ', 'DRD350H', 'DRD350HQ', 'DRD350I', 'DRD350IQ', 'DRD350J', 'DRD350JQ', 'DRD350K', 'DRD360', 'DRD370A', 'DRD370AQ', 'DRD370B', 'DRD370BQ', 'DRD370C', 'DRD370CQ', 'DRD370D', 'DRD370DQ', 'DRD370E', 'DRD370EQ', 'DRD370F', 'DRD370FQ', 'DRD370G', 'DRD370GQ', 'DRD370H', 'DRD370HQ', 'DRD370I', 'DRD370IQ', 'DRD370J', 'DRD370JQ', 'DRD370K', 'DRD370KQ', 'DRD370L', 'DRD370LQ', 'DRD370M', 'DRD370MQ', 'DRD370N', 'DRD370NQ', 'DRD370O', 'DRD370OQ', 'DRD370P', 'DRD370PQ', 'DRD370Q', 'DRD370QQ', 'DRD370R', 'DRD370RQ', 'DRD370S', 'DRD370SQ', 'DRD370T', 'DRD370TQ', 'DRD370U', 'DRD370UQ', 'DRD370V']

In [10]:
data_dietary = data_dietary.drop(['WTDRD1', 'WTDR2D', 'DR1DRSTZ', 'DR1EXMER', 'DRABF', 'DRDINT', 'DR1DBIH', 'DR1DAY', 'DR1LANG', 'DR1MRESP', 'DR1HELP', 'DBQ095Z', 'DBD100', 'DRQSPREP', 'DR1STY', 'DR1SKY', 'DRQSDIET', 'DRQSDT1', 'DRQSDT2', 'DRQSDT3', 'DRQSDT4', 'DRQSDT5', 'DRQSDT6', 'DRQSDT7', 'DRQSDT8', 'DRQSDT9', 'DRQSDT10', 'DRQSDT11', 'DRQSDT12', 'DRQSDT91', 'DR1TNUMF', 'DR1TSFAT', 'DR1TMFAT', 'DR1TPFAT', 'DR1TCHOL', 'DR1TATOC', 'DR1TATOA', 'DR1TRET', 'DR1TVARA', 'DR1TACAR', 'DR1TBCAR', 'DR1TCRYP', 'DR1TLYCO', 'DR1TLZ', 'DR1TVB1', 'DR1TVB2', 'DR1TNIAC', 'DR1TVB6', 'DR1TFOLA', 'DR1TFA', 'DR1TFF', 'DR1TFDFE', 'DR1TCHL', 'DR1TVB12', 'DR1TB12A', 'DR1TVC', 'DR1TVD', 'DR1TVK', 'DR1TCALC', 'DR1TPHOS', 'DR1TMAGN', 'DR1TIRON', 'DR1TZINC', 'DR1TCOPP', 'DR1TSODI', 'DR1TPOTA', 'DR1TSELE', 'DR1TCAFF', 'DR1TTHEO', 'DR1TALCO', 'DR1TMOIS', 'DR1TS040', 'DR1TS060', 'DR1TS080', 'DR1TS100', 'DR1TS120', 'DR1TS140', 'DR1TS160', 'DR1TS180', 'DR1TM161', 'DR1TM181', 'DR1TM201', 'DR1TM221', 'DR1TP182', 'DR1TP183', 'DR1TP184', 'DR1TP204', 'DR1TP205', 'DR1TP225', 'DR1TP226', 'DR1_300', 'DR1_320Z', 'DR1_330Z', 'DR1BWATZ', 'DR1TWSZ', 'DRD340', 'DRD350A', 'DRD350AQ', 'DRD350B', 'DRD350BQ', 'DRD350C', 'DRD350CQ', 'DRD350D', 'DRD350DQ', 'DRD350E', 'DRD350EQ', 'DRD350F', 'DRD350FQ', 'DRD350G', 'DRD350GQ', 'DRD350H', 'DRD350HQ', 'DRD350I', 'DRD350IQ', 'DRD350J', 'DRD350JQ', 'DRD350K', 'DRD360', 'DRD370A', 'DRD370AQ', 'DRD370B', 'DRD370BQ', 'DRD370C', 'DRD370CQ', 'DRD370D', 'DRD370DQ', 'DRD370E', 'DRD370EQ', 'DRD370F', 'DRD370FQ', 'DRD370G', 'DRD370GQ', 'DRD370H', 'DRD370HQ', 'DRD370I', 'DRD370IQ', 'DRD370J', 'DRD370JQ', 'DRD370K', 'DRD370KQ', 'DRD370L', 'DRD370LQ', 'DRD370M', 'DRD370MQ', 'DRD370N', 'DRD370NQ', 'DRD370O', 'DRD370OQ', 'DRD370P', 'DRD370PQ', 'DRD370Q', 'DRD370QQ', 'DRD370R', 'DRD370RQ', 'DRD370S', 'DRD370SQ', 'DRD370T', 'DRD370TQ', 'DRD370U', 'DRD370UQ', 'DRD370V' ], axis=1)

data_dietary = data_dietary.rename(columns={
    'DR1TKCAL': 'Energy (Meals)',
    'DR1TPROT': 'Protein',
    'DR1TCARB' : 'Carbs',
    'DR1TSUGR': 'Sugar',
    'DR1TFIBE': 'Fibre',
    'DR1TTFAT' : 'Total Fat'
})

In [11]:
data_dietary

          SEQN  Energy (Meals)  Protein   Carbs   Sugar  Fibre  Total Fat
0     130378.0          1740.0    80.46  169.66   43.71   10.1      55.07
1     130379.0          2741.0    86.45  314.86  113.58   29.6      67.18
2     130380.0          1995.0    69.86  281.67  114.66   21.1      65.38
3     130381.0          1676.0    54.11  224.98  117.83   11.5      63.57
4     130382.0          1222.0    29.14  194.30  112.99   13.8      39.80
...        ...             ...      ...     ...     ...    ...        ...
8855  142306.0             NaN      NaN     NaN     NaN    NaN        NaN
8856  142307.0          1609.0    71.49  194.91   90.41   16.7      61.66
8857  142308.0             NaN      NaN     NaN     NaN    NaN        NaN
8858  142309.0          4651.0   206.87  531.11  102.17   36.0     189.47
8859  142310.0          1305.0    42.58  107.90   43.59    7.0      56.74

[8860 rows x 7 columns]

Energy (Kcals), The rest is is grams

In [12]:
pd.merge(data_demo, data_dietary, on='SEQN', how='inner').dropna()

,SEQN,Gender,Age in years at screening,Race,Education Level,Martial Status,Ratio of Family Income to Poverty,Energy (Meals),Protein,Carbs,Sugar,Fibre,Total Fat
0,130378.0,1.0,43.0,6.0,5.0,1.0,5.00,1740.0,80.46,169.66,43.71,10.1,55.07
1,130379.0,1.0,66.0,3.0,5.0,1.0,5.00,2741.0,86.45,314.86,113.58,29.6,67.18
2,130380.0,2.0,44.0,2.0,3.0,1.0,1.41,1995.0,69.86,281.67,114.66,21.1,65.38
5,130386.0,1.0,34.0,1.0,4.0,1.0,1.33,2422.0,132.41,207.53,37.89,25.1,116.54
6,130387.0,2.0,68.0,3.0,5.0,3.0,1.32,3849.0,68.93,376.54,227.99,22.0,234.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8850,142301.0,2.0,80.0,3.0,5.0,2.0,1.20,1456.0,65.40,217.01,74.97,34.3,37.08
8851,142302.0,1.0,70.0,3.0,4.0,3.0,2.33,1267.0,27.97,219.74,129.70,5.7,31.80
8852,142303.0,2.0,69.0,7.0,3.0,2.0,0.98,280.0,7.79,39.52,15.15,4.2,10.15
8858,142309.0,1.0,40.0,2.0,4.0,2.0,3.11,4651.0,206.87,531.11,102.17,36.0,189.47
8859,142310.0,2.0,80.0,3.0,3.0,1.0,5.00,1305.0,42.58,107.90,43.59,7.0,56.74

In [13]:
data_body = pd.read_sas('BMX_L.xpt',format='xport')

In [14]:
data_body

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,130378.0,1.0,86.9,NaN,NaN,NaN,NaN,NaN,179.5,NaN,...,42.8,NaN,42.0,NaN,35.7,NaN,98.3,NaN,102.9,NaN
1,130379.0,1.0,101.8,NaN,NaN,NaN,NaN,NaN,174.2,NaN,...,38.5,NaN,38.7,NaN,33.7,NaN,114.7,NaN,112.4,NaN
2,130380.0,1.0,69.4,NaN,NaN,NaN,NaN,NaN,152.9,NaN,...,38.5,NaN,35.5,NaN,36.3,NaN,93.5,NaN,98.0,NaN
3,130381.0,1.0,34.3,NaN,NaN,NaN,NaN,NaN,120.1,NaN,...,NaN,NaN,25.4,NaN,23.4,NaN,70.4,NaN,NaN,NaN
4,130382.0,3.0,13.6,NaN,NaN,1.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,142306.0,1.0,25.3,NaN,NaN,NaN,NaN,NaN,128.0,NaN,...,32.0,NaN,25.0,NaN,19.0,NaN,57.7,NaN,NaN,NaN
8856,142307.0,3.0,NaN,1.0,NaN,NaN,NaN,NaN,143.8,NaN,...,NaN,1.0,34.0,NaN,35.4,NaN,NaN,1.0,NaN,1.0
8857,142308.0,1.0,79.3,NaN,NaN,NaN,NaN,NaN,173.3,NaN,...,41.8,NaN,40.0,NaN,30.6,NaN,98.4,NaN,97.7,NaN
8858,142309.0,1.0,81.9,NaN,NaN,NaN,NaN,NaN,179.1,NaN,...,44.0,NaN,40.0,NaN,30.8,NaN,96.0,NaN,103.3,NaN
8859,142310.0,1.0,72.1,NaN,NaN,NaN,NaN,NaN,161.7,NaN,...,34.2,NaN,34.0,NaN,33.5,NaN,110.8,NaN,115.0,NaN

In [15]:
data_body.columns

Index(['SEQN', 'BMDSTATS', 'BMXWT', 'BMIWT', 'BMXRECUM', 'BMIRECUM', 'BMXHEAD',
       'BMIHEAD', 'BMXHT', 'BMIHT', 'BMXBMI', 'BMDBMIC', 'BMXLEG', 'BMILEG',
       'BMXARML', 'BMIARML', 'BMXARMC', 'BMIARMC', 'BMXWAIST', 'BMIWAIST',
       'BMXHIP', 'BMIHIP'],
      dtype='object')

In [16]:
data_body = data_body.drop(['BMDSTATS', 'BMIWT', 'BMXRECUM', 'BMIRECUM', 'BMXHEAD',
                                  'BMIHEAD', 'BMIHT', 'BMDBMIC', 'BMXLEG', 'BMILEG',
                                  'BMXARML', 'BMIARML', 'BMXARMC', 'BMIARMC', 'BMXWAIST', 'BMIWAIST',
                                  'BMXHIP', 'BMIHIP' ], axis=1)

data_body = data_body.rename(columns={
    'BMXWT': 'Weight (Kgs)',
    'BMXHT': 'Height (cms)',
    'BMXBMI' : 'Body Mass Index'
})

In [17]:
data_body

          SEQN  Weight (Kgs)  Height (cms)  Body Mass Index
0     130378.0          86.9         179.5             27.0
1     130379.0         101.8         174.2             33.5
2     130380.0          69.4         152.9             29.7
3     130381.0          34.3         120.1             23.8
4     130382.0          13.6           NaN              NaN
...        ...           ...           ...              ...
8855  142306.0          25.3         128.0             15.4
8856  142307.0           NaN         143.8              NaN
8857  142308.0          79.3         173.3             26.4
8858  142309.0          81.9         179.1             25.5
8859  142310.0          72.1         161.7             27.6

[8860 rows x 4 columns]

In [22]:
from functools import reduce
dfs = [data_body, data_dietary, data_demo]
final_df = reduce(lambda left, right: pd.merge(left, right, on='SEQN', how='outer'), dfs)

In [24]:
final_df.dropna()

,SEQN,Weight (Kgs),Height (cms),Body Mass Index,Energy (Meals),Protein,Carbs,Sugar,Fibre,Total Fat,Gender,Age in years at screening,Race,Education Level,Martial Status,Ratio of Family Income to Poverty
0,130378.0,86.9,179.5,27.0,1740.0,80.46,169.66,43.71,10.1,55.07,1.0,43.0,6.0,5.0,1.0,5.00
1,130379.0,101.8,174.2,33.5,2741.0,86.45,314.86,113.58,29.6,67.18,1.0,66.0,3.0,5.0,1.0,5.00
2,130380.0,69.4,152.9,29.7,1995.0,69.86,281.67,114.66,21.1,65.38,2.0,44.0,2.0,3.0,1.0,1.41
8,130386.0,90.6,173.3,30.2,2422.0,132.41,207.53,37.89,25.1,116.54,1.0,34.0,1.0,4.0,1.0,1.33
9,130387.0,103.5,155.9,42.6,3849.0,68.93,376.54,227.99,22.0,234.39,2.0,68.0,3.0,5.0,3.0,1.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11923,142301.0,82.2,164.3,30.5,1456.0,65.40,217.01,74.97,34.3,37.08,2.0,80.0,3.0,5.0,2.0,1.20
11924,142302.0,55.8,161.5,21.4,1267.0,27.97,219.74,129.70,5.7,31.80,1.0,70.0,3.0,4.0,3.0,2.33
11925,142303.0,70.8,159.2,27.9,280.0,7.79,39.52,15.15,4.2,10.15,2.0,69.0,7.0,3.0,2.0,0.98
11931,142309.0,81.9,179.1,25.5,4651.0,206.87,531.11,102.17,36.0,189.47,1.0,40.0,2.0,4.0,2.0,3.11
11932,142310.0,72.1,161.7,27.6,1305.0,42.58,107.90,43.59,7.0,56.74,2.0,80.0,3.0,3.0,1.0,5.00

In [25]:
data_cholestrol = pd.read_sas('TCHOL_L.xpt', format = 'xport')

In [26]:
data_cholestrol

          SEQN       WTPH2YR  LBXTC  LBDTCSI
0     130378.0  5.604213e+04  264.0     6.83
1     130379.0  3.743571e+04  214.0     5.53
2     130380.0  8.532884e+04  187.0     4.84
3     130386.0  4.452621e+04  183.0     4.73
4     130387.0  2.274630e+04  203.0     5.25
...        ...           ...    ...      ...
8063  142306.0  5.397605e-79    NaN      NaN
8064  142307.0  6.899418e+04  205.0     5.30
8065  142308.0  5.397605e-79    NaN      NaN
8066  142309.0  4.628442e+04  255.0     6.59
8067  142310.0  5.325082e+04  167.0     4.32

[8068 rows x 4 columns]

In [27]:
data_cholestrol.columns

Index(['SEQN', 'WTPH2YR', 'LBXTC', 'LBDTCSI'], dtype='object')

In [28]:
data_cholestrol = data_cholestrol.drop(['WTPH2YR', 'LBDTCSI' ], axis=1)

data_cholestrol = data_cholestrol.rename(columns={
    'LBXTC': 'Total Cholestrol (mg/dL)'
})

In [29]:
data_cholestrol

          SEQN  Total Cholestrol (mg/dL)
0     130378.0                     264.0
1     130379.0                     214.0
2     130380.0                     187.0
3     130386.0                     183.0
4     130387.0                     203.0
...        ...                       ...
8063  142306.0                       NaN
8064  142307.0                     205.0
8065  142308.0                       NaN
8066  142309.0                     255.0
8067  142310.0                     167.0

[8068 rows x 2 columns]

In [30]:
data_alcohol = pd.read_sas('ALQ_L.xpt', format = 'xport')

In [31]:
data_alcohol

,SEQN,ALQ111,ALQ121,ALQ130,ALQ142,ALQ270,ALQ280,ALQ151,ALQ170
0,130378.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,1.0,2.000000e+00,3.0,5.397605e-79,NaN,NaN,2.0,NaN
2,130380.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,2.0,NaN
3,130386.0,1.0,4.000000e+00,2.0,1.000000e+01,5.397605e-79,1.000000e+01,2.0,5.397605e-79
4,130387.0,1.0,5.397605e-79,NaN,NaN,NaN,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...
6332,142305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6333,142307.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,NaN,2.0,NaN
6334,142308.0,1.0,8.000000e+00,2.0,5.397605e-79,NaN,NaN,2.0,NaN
6335,142309.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6336,142310.0,1.0,3.000000e+00,3.0,3.000000e+00,9.000000e+00,5.397605e-79,2.0,2.000000e+00

In [32]:
data_alcohol.columns

Index(['SEQN', 'ALQ111', 'ALQ121', 'ALQ130', 'ALQ142', 'ALQ270', 'ALQ280',
       'ALQ151', 'ALQ170'],
      dtype='object')

In [33]:
data_alcohol = data_alcohol.drop(['ALQ111', 'ALQ130', 'ALQ142', 'ALQ270', 'ALQ280',
                                  'ALQ151', 'ALQ170' ], axis=1)

data_alcohol = data_alcohol.rename(columns={
    'ALQ121': 'How often drinking'
})

In [35]:
data_alcohol.dropna()

          SEQN  How often drinking
1     130379.0        2.000000e+00
2     130380.0        1.000000e+01
3     130386.0        4.000000e+00
4     130387.0        5.397605e-79
6     130389.0        2.000000e+00
...        ...                 ...
6329  142301.0        1.000000e+01
6330  142302.0        9.000000e+00
6333  142307.0        1.000000e+01
6334  142308.0        8.000000e+00
6336  142310.0        3.000000e+00

[4922 rows x 2 columns]

0 Never, 1 Everyday, 2 Nearly Everyday, 3 three-four times a week, 4 two times a week, 5 once a week, 6 two to three times a month, 7 once a month, 8 seven to eleven times in the last year, 9 3 to 6 times in the last year, 10 one to two times in the last year

In [36]:
data_smoke = pd.read_sas('SMQ_L.xpt', format='xport')

In [37]:
data_smoke

,SEQN,SMQ020,SMQ040,SMD641,SMD650,SMD100MN,SMQ621,SMD630,SMAQUEX2
0,130378.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
1,130379.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
2,130380.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,130384.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,130385.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...
9010,142305.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9011,142307.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
9012,142308.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9013,142309.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9014,142310.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0

In [38]:
data_smoke.columns

Index(['SEQN', 'SMQ020', 'SMQ040', 'SMD641', 'SMD650', 'SMD100MN', 'SMQ621',
       'SMD630', 'SMAQUEX2'],
      dtype='object')

In [39]:
data_smoke = data_smoke.drop(['SMQ040', 'SMD641', 'SMD650', 'SMD100MN', 'SMQ621',
                              'SMD630', 'SMAQUEX2' ], axis=1)

data_smoke = data_smoke.rename(columns={
    'SMQ020': 'Smoked At leat 100 cigarettes'
})

In [40]:
data_smoke

          SEQN  Smoked At leat 100 cigarettes
0     130378.0                            1.0
1     130379.0                            1.0
2     130380.0                            2.0
3     130384.0                            2.0
4     130385.0                            2.0
...        ...                            ...
9010  142305.0                            2.0
9011  142307.0                            1.0
9012  142308.0                            2.0
9013  142309.0                            2.0
9014  142310.0                            1.0

[9015 rows x 2 columns]

1 - yes, 2- no

In [46]:
data_BPCL = pd.read_sas('BPQ_L (1).xpt', format='xport')

In [47]:
data_BPCL.columns

Index(['SEQN', 'BPQ020', 'BPQ030', 'BPQ150', 'BPQ080', 'BPQ101D'], dtype='object')

In [48]:
data_BPCL = data_BPCL.drop(['BPQ020', 'BPQ030', 'BPQ150' ], axis=1)

data_BPCL = data_BPCL.rename(columns={
    'BPQ080': 'Doctor Told had high cholestrol level',
    'BPQ101D': 'Taking meds for cholestrol'
})

In [49]:
data_BPCL

,SEQN,Doctor Told had high cholestrol level,Taking meds for cholestrol
0,130378.0,2.0,2.0
1,130379.0,2.0,2.0
2,130380.0,1.0,1.0
3,130384.0,2.0,2.0
4,130385.0,2.0,2.0
...,...,...,...
8496,142305.0,1.0,1.0
8497,142307.0,1.0,1.0
8498,142308.0,2.0,2.0
8499,142309.0,2.0,2.0
8500,142310.0,2.0,2.0

1 - Yes, 2 - No

In [58]:
data_HDL = pd.read_sas('HDL_L.xpt', format='xport')

In [59]:
data_HDL.columns

Index(['SEQN', 'WTPH2YR', 'LBDHDD', 'LBDHDDSI'], dtype='object')

In [60]:
data_HDL = data_HDL.drop(['WTPH2YR', 'LBDHDDSI' ], axis=1)

data_HDL = data_HDL.rename(columns={
    'LBDHDD': 'HDL Cholestrol (md/dL)'
})

In [61]:
data_HDL

          SEQN  HDL Cholestrol (md/dL)
0     130378.0                    45.0
1     130379.0                    60.0
2     130380.0                    49.0
3     130386.0                    46.0
4     130387.0                    42.0
...        ...                     ...
8063  142306.0                     NaN
8064  142307.0                    79.0
8065  142308.0                     NaN
8066  142309.0                    54.0
8067  142310.0                    48.0

[8068 rows x 2 columns]

In [62]:
from functools import reduce
dfs = [data_body, data_dietary, data_demo, data_alcohol, data_smoke, data_cholestrol, data_BPCL, data_HDL]
final_df = reduce(lambda left, right: pd.merge(left, right, on='SEQN', how='outer'), dfs)

In [63]:
final_df.dropna()

,SEQN,Weight (Kgs),Height (cms),Body Mass Index,Energy (Meals),Protein,Carbs,Sugar,Fibre,Total Fat,...,Race,Education Level,Martial Status,Ratio of Family Income to Poverty,How often drinking,Smoked At leat 100 cigarettes,Total Cholestrol (mg/dL),Doctor Told had high cholestrol level,Taking meds for cholestrol,HDL Cholestrol (md/dL)
1,130379.0,101.8,174.2,33.5,2741.0,86.45,314.86,113.58,29.6,67.18,...,3.0,5.0,1.0,5.00,2.000000e+00,1.0,214.0,2.0,2.0,60.0
2,130380.0,69.4,152.9,29.7,1995.0,69.86,281.67,114.66,21.1,65.38,...,2.0,3.0,1.0,1.41,1.000000e+01,2.0,187.0,1.0,1.0,49.0
8,130386.0,90.6,173.3,30.2,2422.0,132.41,207.53,37.89,25.1,116.54,...,1.0,4.0,1.0,1.33,4.000000e+00,1.0,183.0,2.0,2.0,46.0
9,130387.0,103.5,155.9,42.6,3849.0,68.93,376.54,227.99,22.0,234.39,...,3.0,5.0,3.0,1.32,5.397605e-79,2.0,203.0,1.0,2.0,42.0
14,130392.0,98.7,151.5,43.0,2108.0,85.65,216.92,104.13,13.5,104.50,...,3.0,5.0,1.0,3.04,8.000000e+00,2.0,191.0,2.0,2.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11921,142299.0,113.8,178.5,35.7,2242.0,91.44,214.03,73.75,18.6,115.08,...,1.0,4.0,1.0,3.28,9.000000e+00,1.0,167.0,2.0,2.0,33.0
11922,142300.0,75.2,151.8,32.6,2768.0,123.93,339.15,100.23,26.2,90.08,...,1.0,3.0,1.0,0.68,6.000000e+00,1.0,167.0,2.0,2.0,55.0
11923,142301.0,82.2,164.3,30.5,1456.0,65.40,217.01,74.97,34.3,37.08,...,3.0,5.0,2.0,1.20,1.000000e+01,1.0,138.0,1.0,9.0,48.0
11924,142302.0,55.8,161.5,21.4,1267.0,27.97,219.74,129.70,5.7,31.80,...,3.0,4.0,3.0,2.33,9.000000e+00,1.0,174.0,1.0,1.0,60.0
11932,142310.0,72.1,161.7,27.6,1305.0,42.58,107.90,43.59,7.0,56.74,...,3.0,3.0,1.0,5.00,3.000000e+00,1.0,167.0,2.0,2.0,48.0